%% Meteorological preprocessing and LNPP/CLNPP calculation
% MATLAB R2018b

clc;
clear;

%% 1. Files

script_dir = fileparts(mfilename('fullpath'));

if isempty(script_dir)
    script_dir = pwd;
end

input_file = fullfile( ...
    script_dir, ...
    'meteorological_example.mat');

output_file = fullfile( ...
    script_dir, ...
    'meteorological_example_LNPP_CLNPP.mat');

%% 2. Parameters

angstrom_a = 0.143;
angstrom_b = 0.585;

T_low  = 8;
T_opt  = 25;
T_high = 38;

VPD_low  = 0.65;
VPD_high = 4.3;

radiation_coefficient = 17.6;% Composite coefficient calculated from Eq. (4)
window_size = 7;

%% 3. Load data

S = load(input_file, 'extracted_data');

if ~isfield(S, 'extracted_data')
    error('Variable extracted_data was not found.');
end

T = S.extracted_data;

if ~istable(T)
    error('extracted_data must be a table.');
end

required_variables = { ...
    'Station_Id_C', ...
    'Lon', ...
    'Lat', ...
    'Year', ...
    'Mon', ...
    'Day', ...
    'TEM_Avg', ...
    'TEM_Min', ...
    'TEM_Max', ...
    'SSH', ...
    'PRE_Time_2020', ...
    'RHU_Avg'};

if ~all(ismember(required_variables, T.Properties.VariableNames))
    error('Required meteorological variables are missing.');
end

%% 4. Convert variables to numeric

Station = toNumeric(T.Station_Id_C);

Lon   = toNumeric(T.Lon);
Lat   = toNumeric(T.Lat);

Year  = toNumeric(T.Year);
Month = toNumeric(T.Mon);
Day   = toNumeric(T.Day);

Tmean = toNumeric(T.TEM_Avg);
Tmin  = toNumeric(T.TEM_Min);
Tmax  = toNumeric(T.TEM_Max);

SSH = toNumeric(T.SSH);
PRE = toNumeric(T.PRE_Time_2020);
RH  = toNumeric(T.RHU_Avg);

%% 5. Date check

valid_date = ...
    isfinite(Station) & ...
    isfinite(Year) & ...
    isfinite(Month) & ...
    isfinite(Day) & ...
    Month >= 1 & Month <= 12 & ...
    Day >= 1 & Day <= 31;

if any(~valid_date)

    fprintf('Removed rows with invalid date fields: %d\n', ...
        sum(~valid_date));

end

Station = Station(valid_date);

Lon = Lon(valid_date);
Lat = Lat(valid_date);

Year  = Year(valid_date);
Month = Month(valid_date);
Day   = Day(valid_date);

Tmean = Tmean(valid_date);
Tmin  = Tmin(valid_date);
Tmax  = Tmax(valid_date);

SSH = SSH(valid_date);
PRE = PRE(valid_date);
RH  = RH(valid_date);

Date = datetime(Year, Month, Day);

date_consistent = ...
    year(Date) == Year & ...
    month(Date) == Month & ...
    day(Date) == Day;

if any(~date_consistent)
    error('Invalid calendar dates were detected.');
end

%% 6. Check duplicate station-date records

date_number = datenum(Date);

key = [Station, date_number];

[~, unique_index] = unique(key, 'rows');

if numel(unique_index) ~= size(key,1)
    error('Duplicate Station-Date records were detected.');
end

%% 7. Quality control

[Tmean, flag_tmean] = ...
    cleanRegularVariable(Tmean, -60, 60);

[Tmin, flag_tmin] = ...
    cleanRegularVariable(Tmin, -60, 60);

[Tmax, flag_tmax] = ...
    cleanRegularVariable(Tmax, -60, 60);

[SSH, flag_ssh] = ...
    cleanRegularVariable(SSH, 0, 24);

[RH, flag_rh] = ...
    cleanRegularVariable(RH, 0, 100);

[PRE, PRE_trace, flag_pre] = ...
    cleanPrecipitation(PRE);

%% 8. Temperature consistency

bad_minmax = ...
    isfinite(Tmin) & ...
    isfinite(Tmax) & ...
    Tmin > Tmax;

flag_tmin(bad_minmax) = true;
flag_tmax(bad_minmax) = true;

Tmin(bad_minmax) = NaN;
Tmax(bad_minmax) = NaN;

bad_mean = ...
    isfinite(Tmean) & ...
    isfinite(Tmin) & ...
    isfinite(Tmax) & ...
    (Tmean < Tmin | Tmean > Tmax);

flag_tmean(bad_mean) = true;
Tmean(bad_mean) = NaN;

%% 9. Station processing

station_list = unique(Station);

processed_data = table();
qc_summary = table();

for s = 1:numel(station_list)

    sid = station_list(s);

    idx = Station == sid;

    station_date = Date(idx);

    first_year = min(year(station_date));
    last_year  = max(year(station_date));

    full_date = ( ...
        datetime(first_year,1,1): ...
        caldays(1): ...
        datetime(last_year,12,31))';

    n = numel(full_date);

    lon_values = Lon(idx);
    lon_values = lon_values(isfinite(lon_values));

    lat_values = Lat(idx);
    lat_values = lat_values(isfinite(lat_values));

    if isempty(lon_values) || isempty(lat_values)
        error('Station %d has no valid coordinates.', sid);
    end

    station_lon = median(lon_values);
    station_lat = median(lat_values);

    tmean_full = NaN(n,1);
    tmin_full  = NaN(n,1);
    tmax_full  = NaN(n,1);

    ssh_full = NaN(n,1);
    pre_full = NaN(n,1);
    rh_full  = NaN(n,1);

    pre_trace_full = false(n,1);

    [found, loc] = ismember(station_date, full_date);

    if ~all(found)
        error('Date matching failed for station %d.', sid);
    end

    tmean_full(loc) = Tmean(idx);
    tmin_full(loc)  = Tmin(idx);
    tmax_full(loc)  = Tmax(idx);

    ssh_full(loc) = SSH(idx);
    pre_full(loc) = PRE(idx);
    rh_full(loc)  = RH(idx);

    pre_trace_full(loc) = PRE_trace(idx);

    missing_calendar_days = ...
        n - numel(station_date);

    missing_before = [ ...
        sum(~isfinite(tmean_full)); ...
        sum(~isfinite(tmin_full)); ...
        sum(~isfinite(tmax_full)); ...
        sum(~isfinite(ssh_full)); ...
        sum(~isfinite(pre_full)); ...
        sum(~isfinite(rh_full))];

    flagged_source = [ ...
        sum(flag_tmean(idx)); ...
        sum(flag_tmin(idx)); ...
        sum(flag_tmax(idx)); ...
        sum(flag_ssh(idx)); ...
        sum(flag_pre(idx)); ...
        sum(flag_rh(idx))];

    trace_source = [ ...
        0; ...
        0; ...
        0; ...
        0; ...
        sum(PRE_trace(idx)); ...
        0];

    %% 10. Fill missing daily values

    tmean_full = fillLocal(tmean_full, window_size);
    tmin_full  = fillLocal(tmin_full, window_size);
    tmax_full  = fillLocal(tmax_full, window_size);

    ssh_full = fillLocal(ssh_full, window_size);
    rh_full  = fillLocal(rh_full, window_size);

    % Missing precipitation is retained as NaN.

    missing_after = [ ...
        sum(~isfinite(tmean_full)); ...
        sum(~isfinite(tmin_full)); ...
        sum(~isfinite(tmax_full)); ...
        sum(~isfinite(ssh_full)); ...
        sum(~isfinite(pre_full)); ...
        sum(~isfinite(rh_full))];

    required_missing = ...
        missing_after([1 2 3 4 6]);

    if any(required_missing > 0)

        error(['Unresolved missing values remain ' ...
            'at station %d.'], sid);

    end

    %% 11. Date variables

    year_full  = year(full_date);
    month_full = month(full_date);
    day_full   = day(full_date);

    doy = day(full_date, 'dayofyear');

    %% 12. Solar radiation

    lat_rad = station_lat * pi / 180;

    solar_declination = ...
        0.409 .* ...
        sin(2 .* pi .* doy ./ 365 - 1.39);

    acos_input = ...
        -tan(lat_rad) .* tan(solar_declination);

    acos_input(acos_input > 1) = 1;
    acos_input(acos_input < -1) = -1;

    sunset_hour_angle = ...
        acos(acos_input);

    daylight_hours = ...
        24 .* sunset_hour_angle ./ pi;

    distance_factor = ...
        1 + ...
        0.033 .* cos(2 .* pi .* doy ./ 365);

    Ra = ...
        37.6 .* ...
        distance_factor .* ...
        ( ...
        sunset_hour_angle .* ...
        sin(lat_rad) .* ...
        sin(solar_declination) + ...
        cos(lat_rad) .* ...
        cos(solar_declination) .* ...
        sin(sunset_hour_angle) ...
        );

    Rad = ...
        ( ...
        angstrom_a + ...
        angstrom_b .* ...
        ssh_full ./ daylight_hours ...
        ) .* Ra;

    %% 13. Saturation vapor pressure and VPD

    es = ...
        0.61078 .* ...
        exp( ...
        (17.269 .* tmean_full) ./ ...
        (tmean_full + 237.3) ...
        );

    ea = ...
        (rh_full ./ 100) .* es;

    VPD = es - ea;

    VPD(VPD < 0) = 0;

    %% 14. Temperature response

    ft = zeros(n,1);

    idx_low = ...
        tmean_full >= T_low & ...
        tmean_full < T_opt;

    ft(idx_low) = ...
        ( ...
        tmean_full(idx_low) - T_low ...
        ) ./ ...
        (T_opt - T_low);

    idx_high = ...
        tmean_full >= T_opt & ...
        tmean_full <= T_high;

    ft(idx_high) = ...
        ( ...
        T_high - tmean_full(idx_high) ...
        ) ./ ...
        (T_high - T_opt);

    %% 15. VPD response

    fw = ones(n,1);

    fw(VPD > VPD_high) = 0;

    idx_vpd = ...
        VPD >= VPD_low & ...
        VPD <= VPD_high;

    fw(idx_vpd) = ...
        1 - ...
        ( ...
        VPD(idx_vpd) - VPD_low ...
        ) ./ ...
        (VPD_high - VPD_low);

    %% 16. Daily LNPP

    photo_potential = ...
        radiation_coefficient .* Rad;

    temperature_limited = ...
        photo_potential .* ft;

    LNPP = ...
        temperature_limited .* fw;

    %% 17. Annual cumulative LNPP

    CLNPP = NaN(n,1);

    years_station = unique(year_full);

    for y = 1:numel(years_station)

        current_year = years_station(y);

        iy = year_full == current_year;

        CLNPP(iy) = cumsum(LNPP(iy));

    end

    %% 18. Output table

    station_column = repmat(sid, n, 1);
    lon_column = repmat(station_lon, n, 1);
    lat_column = repmat(station_lat, n, 1);

    station_table = table( ...
        station_column, ...
        lon_column, ...
        lat_column, ...
        year_full, ...
        month_full, ...
        day_full, ...
        doy, ...
        tmean_full, ...
        tmin_full, ...
        tmax_full, ...
        ssh_full, ...
        pre_full, ...
        pre_trace_full, ...
        rh_full, ...
        Rad, ...
        es, ...
        ea, ...
        VPD, ...
        ft, ...
        fw, ...
        photo_potential, ...
        temperature_limited, ...
        LNPP, ...
        CLNPP, ...
        'VariableNames', { ...
        'Station', ...
        'Lon', ...
        'Lat', ...
        'Year', ...
        'Month', ...
        'Day', ...
        'DOY', ...
        'Tmean', ...
        'Tmin', ...
        'Tmax', ...
        'SSH', ...
        'PRE', ...
        'PRE_trace', ...
        'RH', ...
        'Rad', ...
        'es', ...
        'ea', ...
        'VPD', ...
        'ft', ...
        'fw', ...
        'PhotoPotential', ...
        'TemperatureLimited', ...
        'LNPP', ...
        'CLNPP'});

    processed_data = ...
        [processed_data; station_table]; %#ok<AGROW>

    %% 19. QC summary

    variable_name = { ...
        'Tmean'; ...
        'Tmin'; ...
        'Tmax'; ...
        'SSH'; ...
        'PRE'; ...
        'RH'};

    filled_values = ...
        missing_before - missing_after;

    station_qc = table( ...
        repmat(sid,6,1), ...
        variable_name, ...
        repmat(missing_calendar_days,6,1), ...
        flagged_source, ...
        trace_source, ...
        missing_before, ...
        filled_values, ...
        missing_after, ...
        'VariableNames', { ...
        'Station', ...
        'Variable', ...
        'MissingCalendarDays', ...
        'FlaggedSourceValues', ...
        'TracePrecipitationValues', ...
        'MissingBeforeFilling', ...
        'FilledValues', ...
        'MissingAfterFilling'});

    qc_summary = ...
        [qc_summary; station_qc]; %#ok<AGROW>

end

%% 20. Parameters

parameters = struct();

parameters.Angstrom_a = angstrom_a;
parameters.Angstrom_b = angstrom_b;

parameters.T_low = T_low;
parameters.T_opt = T_opt;
parameters.T_high = T_high;

parameters.VPD_low = VPD_low;
parameters.VPD_high = VPD_high;

parameters.RadiationCoefficient = ...
    radiation_coefficient;

parameters.ImputationWindowDays = ...
    window_size;

parameters.TracePrecipitationCode = ...
    999990;

parameters.MissingValueThreshold = ...
    9000;

%% 21. Save

save( ...
    output_file, ...
    'processed_data', ...
    'qc_summary', ...
    'parameters', ...
    '-v7.3');
fprintf('\nPreprocessing completed.\n');
fprintf('Output file:\n%s\n', output_file);

fprintf('\nNumber of stations: %d\n', ...
    numel(unique(processed_data.Station)));

fprintf('Number of rows: %d\n\n', ...
    height(processed_data));

disp(qc_summary);


%% Local functions

function x = toNumeric(x)

    if isnumeric(x) || islogical(x)

        x = double(x);
        return;

    end

    if iscategorical(x)
        x = cellstr(x);
    end

    if ischar(x)
        x = cellstr(x);
    end

    x = str2double(string(x));

end


function [x, flagged] = ...
    cleanRegularVariable(x, lower_limit, upper_limit)

    x = double(x);

    nonfinite = ...
        ~isfinite(x);

    characteristic_value = ...
        isfinite(x) & ...
        abs(x) >= 9000;

    outside_range = ...
        isfinite(x) & ...
        ~characteristic_value & ...
        ( ...
        x < lower_limit | ...
        x > upper_limit ...
        );

    flagged = ...
        nonfinite | ...
        characteristic_value | ...
        outside_range;

    x(flagged) = NaN;

end


function [x, trace_flag, missing_flag] = ...
    cleanPrecipitation(x)

    x = double(x);

    trace_flag = ...
        x == 999990;

    nonfinite = ...
        ~isfinite(x);

    characteristic_value = ...
        isfinite(x) & ...
        abs(x) >= 9000 & ...
        ~trace_flag;

    outside_range = ...
        isfinite(x) & ...
        ~trace_flag & ...
        ~characteristic_value & ...
        (x < 0 | x > 2000);

    missing_flag = ...
        nonfinite | ...
        characteristic_value | ...
        outside_range;

    x(trace_flag) = 0;
    x(missing_flag) = NaN;

end


function filled = ...
    fillLocal(x, window_size)

    x = double(x);

    filled = x;

    n = numel(x);

    missing_index = ...
        find(~isfinite(x));

    half_window = ...
        floor(window_size / 2);

    for k = 1:numel(missing_index)

        i = missing_index(k);

        start_index = ...
            max(1, i - half_window);

        end_index = ...
            min(n, i + half_window);

        local_data = ...
            x(start_index:end_index);

        local_data = ...
            local_data(isfinite(local_data));

        if ~isempty(local_data)

            filled(i) = mean(local_data);
            continue;

        end

        start_index = ...
            max(1, i - window_size);

        end_index = ...
            min(n, i + window_size);

        local_data = ...
            x(start_index:end_index);

        local_data = ...
            local_data(isfinite(local_data));

        if ~isempty(local_data)

            filled(i) = mean(local_data);
            continue;

        end

        previous_index = ...
            find( ...
            isfinite(x(1:i-1)), ...
            1, ...
            'last');

        next_relative = ...
            find( ...
            isfinite(x(i+1:end)), ...
            1, ...
            'first');

        if ...
                ~isempty(previous_index) && ...
                ~isempty(next_relative)

            next_index = ...
                i + next_relative;

            filled(i) = ...
                mean( ...
                [ ...
                x(previous_index), ...
                x(next_index) ...
                ]);

        elseif ~isempty(previous_index)

            filled(i) = ...
                x(previous_index);

        elseif ~isempty(next_relative)

            next_index = ...
                i + next_relative;

            filled(i) = ...
                x(next_index);

        end

    end

end